#!/bin/sh
# Runs once on an empty data directory. Creates the owned databases with their
# separate app/migrator roles (architecture.md naming) and Temporal's stores.
# ANVILKIT_DEV_PASSWORD is generated by up.sh into .local/dev/postgres.env.
set -eu
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d postgres <<SQL
CREATE ROLE temporal LOGIN PASSWORD '${ANVILKIT_DEV_PASSWORD}';
CREATE DATABASE temporal OWNER temporal;
CREATE DATABASE temporal_visibility OWNER temporal;
SQL
for domain in control knowledge mcp; do
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d postgres <<SQL
CREATE ROLE anvilkit_${domain}_app LOGIN PASSWORD '${ANVILKIT_DEV_PASSWORD}';
CREATE ROLE anvilkit_${domain}_migrator LOGIN PASSWORD '${ANVILKIT_DEV_PASSWORD}';
CREATE DATABASE anvilkit_${domain} OWNER anvilkit_${domain}_migrator;
SQL
  # The app role must not be able to create objects in the domain schema.
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "anvilkit_${domain}" <<SQL
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO anvilkit_${domain}_migrator;
SQL
done
