#!/bin/sh
# Offline and cluster checks of the P09 admission policies.
#
#   sh deploy/policies/check.sh              # offline: kyverno apply (CLI) against the launcher's fixtures and their mutations
#   sh deploy/policies/check.sh --cluster    # in addition: server-side dry-run admission against the development cluster
#
# The fixtures are rendered by the launcher (services/agent/workflow,
# TestRenderPolicyFixtures) into deploy/policies/tests/resources; the negative
# cases are derived from them by tests/mutate.py. Offline results are policy
# evaluation by the pinned Kyverno CLI (1.19.1), not admission; --cluster asks the
# development cluster's admission chain (Kyverno's webhook) with server-side dry
# runs and records that separately: Pods with the cluster administrator's context
# (the launcher identity cannot create Pods), Jobs with the launcher's own
# identity (ANVILKIT_LAUNCHER_KUBECONFIG, the kubeconfig deploy/dev/up.sh writes),
# which is what the Job policy and the autogenerated template rules admit or deny
# for the real launcher. Exit 1 on any unexpected outcome.
set -eu
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
POLICIES="$ROOT/deploy/policies"
KYVERNO=${ANVILKIT_KYVERNO_CLI:-$ROOT/.local/dev/kyverno/kyverno}
PY=${ANVILKIT_PYTHON_ENV:-$ROOT/.local/verification-venv/bin/python}
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
export PATH="$PATH:$(go env GOPATH)/bin"

test -x "$KYVERNO" || { echo "UNEXECUTED: kyverno CLI not found at $KYVERNO (deploy/dev/up.sh downloads 1.19.1)" >&2; exit 2; }
"$KYVERNO" version | head -1
(cd "$ROOT/services/agent/workflow" && ANVILKIT_RENDER_POLICY_FIXTURES="$POLICIES/tests/resources" go test -count=1 -run TestRenderPolicyFixtures ./internal/adapters/kubernetes/ >/dev/null)
"$PY" "$POLICIES/tests/mutate.py" "$POLICIES/tests/resources" "$WORK/cases"
# kyverno apply evaluates namespace selectors from a values file offline.
cat > "$WORK/values.yaml" <<VALUES
apiVersion: cli.kyverno.io/v1alpha1
kind: Values
metadata:
  name: anvilkit-components
namespaceSelector:
  - name: anvilkit-components
    labels:
      kubernetes.io/metadata.name: anvilkit-components
VALUES
failures=0
total=0
for f in "$WORK"/cases/*.yaml; do
  case=$(basename "$f" .yaml)
  expect=$("$PY" -c "import json,sys; print(json.load(open('$WORK/cases/expectations.json'))['$case'])")
  total=$((total+1))
  out=$("$KYVERNO" apply "$POLICIES/kyverno/anvilkit-components-jobs.yaml" "$POLICIES/kyverno/anvilkit-components-registries.dev.yaml" --resource "$f" --values-file "$WORK/values.yaml" 2>&1 || true)
  if echo "$out" | grep -qE 'fail: [1-9]'; then got=fail; elif echo "$out" | grep -qE 'pass: [1-9]'; then got=pass; else got="error"; fi
  if [ "$got" = "$expect" ]; then
    printf 'PASS offline %-36s %s\n' "$case" "$got"
  else
    printf 'FAIL offline %-36s expected %s, got %s\n' "$case" "$expect" "$got"
    echo "$out" | tail -n 6 | sed 's/^/      | /'
    failures=$((failures+1))
  fi
done
if [ "${1:-}" = "--cluster" ]; then
  CTX=${ANVILKIT_DEV_KUBE_CONTEXT:-kind-anvilkit-dev}
  LAUNCHER=${ANVILKIT_LAUNCHER_KUBECONFIG:-$ROOT/.local/dev/launcher.kubeconfig}
  test -r "$LAUNCHER" || { echo "UNEXECUTED: launcher kubeconfig not found at $LAUNCHER (deploy/dev/up.sh writes it)" >&2; exit 2; }
  gvisor=yes
  kubectl --context "$CTX" get runtimeclass gvisor >/dev/null 2>&1 || gvisor=no
  for f in "$WORK"/cases/*.yaml; do
    case=$(basename "$f" .yaml)
    expect=$("$PY" -c "import json,sys; print(json.load(open('$WORK/cases/expectations.json'))['$case'])")
    if [ "$case" = valid-candidate-pod ] && [ "$gvisor" = no ]; then
      # The API server refuses a Pod whose RuntimeClass does not exist: on a
      # cluster without gVisor the candidate profile cannot be admitted at
      # all, which is the state P09 records (the profile stays disabled).
      printf 'UNEXECUTED cluster %-29s no gVisor RuntimeClass on this cluster; the API server refuses the Pod before Kyverno decides\n' "$case"
      continue
    fi
    total=$((total+1))
    if grep -q '^kind: Job$' "$f"; then
      who=launcher
      if out=$(kubectl --kubeconfig "$LAUNCHER" create --dry-run=server -f "$f" 2>&1); then got=pass; else got=fail; fi
    else
      who=admin
      if out=$(kubectl --context "$CTX" create --dry-run=server -f "$f" 2>&1); then got=pass; else got=fail; fi
    fi
    if [ "$got" = "$expect" ]; then
      printf 'PASS cluster/%-8s %-36s %s\n' "$who" "$case" "$got"
    else
      printf 'FAIL cluster/%-8s %-36s expected %s, got %s\n' "$who" "$case" "$expect" "$got"
      echo "$out" | tail -n 4 | sed 's/^/      | /'
      failures=$((failures+1))
    fi
  done
fi
echo "policy checks: $total cases, $failures failures"
[ "$failures" -eq 0 ]
