#!/usr/bin/env python3
"""Generation entry point of the parent checkout: two separate generators.

Usage:
  python3 tools/generate-contracts.py [--check] [--only contracts|sqlc]

  contracts   The contract bindings (Go, TypeScript, Python) are generated by the
              contracts repository itself: contracts/tools/generate.py, run here under
              the same pinned interpreter, reads only contracts/ and writes only
              contracts/{go,ts,python}. The sources and the generated packages have one
              authority, the anvilkit-agent-contracts submodule.
  sqlc        Control's data-access code (services/anvilkit-agent-control/internal/
              adapters/postgres/sqlc) is generated by sqlc 1.27.0 from the reviewed
              queries and the Control migrations (jobs/migration/.../sql/control, the
              schema the migration Job applies). It is service-owned generation and has
              nothing to do with the contract sources; it stays here only while Control
              lives in this checkout.

--check regenerates each output into a scratch tree and fails on drift; without it both
outputs are rewritten in place. tools/run-verification.py runs `--check`.
"""
from __future__ import annotations

import argparse
import filecmp
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import pyenv_check  # noqa: E402

pyenv_check.require("datamodel_code_generator")

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
CONTROL = ROOT / "services/anvilkit-agent-control"
CONTROL_SQL = ROOT / "jobs/migration/internal/migrate/sql/control"
SQLC_OUT = "internal/adapters/postgres/sqlc"
SQLC_PIN = "1.27.0"


def sqlc_binary() -> pathlib.Path:
    gobin = pathlib.Path(subprocess.run(["go", "env", "GOPATH"], capture_output=True, text=True, check=True).stdout.strip()) / "bin"
    candidate = gobin / "sqlc"
    if not candidate.exists():
        found = shutil.which("sqlc")
        if not found:
            sys.exit("FAIL: sqlc is not installed (go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0)")
        candidate = pathlib.Path(found)
    out = subprocess.run([str(candidate), "version"], capture_output=True, text=True)
    m = re.search(r"v(\d+\.\d+\.\d+)", (out.stdout + out.stderr).strip())
    if not m or m.group(1) != SQLC_PIN:
        sys.exit(f"FAIL: sqlc at {candidate} reports {(out.stdout + out.stderr).strip()!r}; pinned {SQLC_PIN}")
    return candidate


def generate_contracts(check: bool) -> int:
    tool = CONTRACTS / "tools" / "generate.py"
    if not tool.exists():
        print("FAIL contracts/tools/generate.py is missing (the contracts submodule is not checked out)")
        return 1
    p = subprocess.run([sys.executable, str(tool), *(["--check"] if check else [])], cwd=CONTRACTS)
    return p.returncode


def generate_sqlc(check: bool) -> int:
    if not (CONTROL / "sqlc.yaml").exists():
        print("FAIL services/anvilkit-agent-control/sqlc.yaml is missing")
        return 1
    sqlc = sqlc_binary()
    env = dict(os.environ)
    if not check:
        subprocess.run([str(sqlc), "generate", "-f", str(CONTROL / "sqlc.yaml")], cwd=CONTROL, env=env, check=True)
        print(f"generated: services/anvilkit-agent-control/{SQLC_OUT}")
        return 0
    with tempfile.TemporaryDirectory() as scratch:
        # Mirror the configuration, the queries and the schema so the check never
        # touches the checkout (sqlc resolves paths relative to its configuration file).
        scratch_control = pathlib.Path(scratch) / "services/anvilkit-agent-control"
        shutil.copytree(CONTROL / "internal/adapters/postgres/queries", scratch_control / "internal/adapters/postgres/queries")
        shutil.copyfile(CONTROL / "sqlc.yaml", scratch_control / "sqlc.yaml")
        shutil.copytree(CONTROL_SQL, pathlib.Path(scratch) / "jobs/migration/internal/migrate/sql/control")
        p = subprocess.run([str(sqlc), "generate", "-f", str(scratch_control / "sqlc.yaml")], cwd=scratch_control, env=env, capture_output=True, text=True)
        if p.returncode != 0:
            print("FAIL sqlc generate:", (p.stdout + p.stderr).strip()[-1500:])
            return 1
        diffs: list[str] = []
        cmp = filecmp.dircmp(scratch_control / SQLC_OUT, CONTROL / SQLC_OUT)
        diffs += [f"missing in checkout: {n}" for n in cmp.left_only]
        diffs += [f"stale in checkout: {n}" for n in cmp.right_only]
        diffs += [f"differs: {n}" for n in cmp.diff_files]
        for d in diffs:
            print("FAIL", f"services/anvilkit-agent-control/{SQLC_OUT}: {d}")
        print(f"sqlc check: {len(diffs)} differences")
        return 1 if diffs else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if regeneration would change any checked-in output")
    ap.add_argument("--only", choices=["contracts", "sqlc"], action="append")
    a = ap.parse_args()
    rc = 0
    if not a.only or "contracts" in a.only:
        rc |= generate_contracts(a.check)
    if not a.only or "sqlc" in a.only:
        rc |= generate_sqlc(a.check)
    return 1 if rc else 0


if __name__ == "__main__":
    sys.exit(main())
