#!/usr/bin/env python3
"""Generation entry point of the parent checkout: two separate generators.

Usage:
  python3 tools/generate-contracts.py [--check] [--only contracts|sqlc]

  contracts   The contract bindings (Go, TypeScript, Python) are generated by the
              contracts repository itself: contracts/tools/generate.py, run here under
              the same pinned interpreter, reads only contracts/ and writes only
              contracts/{go,ts,python}. The sources and the generated packages have one
              authority, the anvilkit-agent-contracts submodule.
  sqlc        Control's data-access code is generated by sqlc 1.27.0 from its reviewed
              queries and its own migration source (internal/migrate/sql, the schema the
              service's migration Job applies). Since the relocation of Control into its
              repository (services/agent/control) that generation and its drift check are
              service-owned: services/agent/control/tools/sqlc.sh [--check]; this entry point
              only delegates to it.

--check regenerates each output into a scratch tree and fails on drift; without it both
outputs are rewritten in place. tools/run-verification.py runs `--check`.
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import pyenv_check  # noqa: E402

pyenv_check.require("datamodel_code_generator")

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
CONTROL = ROOT / "services/agent/control"


def generate_contracts(check: bool) -> int:
    tool = CONTRACTS / "tools" / "generate.py"
    if not tool.exists():
        print("FAIL contracts/tools/generate.py is missing (the contracts submodule is not checked out)")
        return 1
    p = subprocess.run([sys.executable, str(tool), *(["--check"] if check else [])], cwd=CONTRACTS)
    return p.returncode


def generate_sqlc(check: bool) -> int:
    tool = CONTROL / "tools" / "sqlc.sh"
    if not tool.exists():
        print("FAIL services/agent/control/tools/sqlc.sh is missing (the Control submodule is not checked out)")
        return 1
    p = subprocess.run(["sh", str(tool), *(["--check"] if check else [])], cwd=CONTROL)
    return p.returncode


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if regeneration would change any checked-in output")
    ap.add_argument("--only", choices=["contracts", "sqlc"], action="append")
    a = ap.parse_args()
    rc = 0
    if not a.only or "contracts" in a.only:
        rc |= generate_contracts(a.check)
    if not a.only or "sqlc" in a.only:
        rc |= generate_sqlc(a.check)
    return 1 if rc else 0


if __name__ == "__main__":
    sys.exit(main())
