# CloudPirates valkey 0.25.11 (Apache-2.0, LICENSE in this directory) with one AnvilKit
# patch: the Sentinel container no longer prints its configuration, which holds the
# queue password (templates/statefulset.yaml). Everything else is upstream.
annotations:
  artifacthub.io/category: database
  artifacthub.io/changes: |-
    - kind: changed
      description: '[oliver006/redis_exporter] Update metrics.image.repository to v1.91.1
        (#1701)'
      links:
      - name: Pull Request
        url: https://github.com/CloudPirates-io/helm-charts/pull/1701
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Valkey
      url: https://valkey.io
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/valkey
    - name: Application
      url: https://github.com/valkey-io/valkey
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  license: Apache-2.0
apiVersion: v2
appVersion: 9.1.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.2.1
description: High performance in-memory data structure store, fork of Redis. Valkey
  is an open-source, high-performance key/value datastore that supports a variety
  of workloads such as caching, message queues, and can act as a primary database.
home: https://www.valkey.io
icon: https://a.storyblok.com/f/143071/512x512/5242c0e31a/valkey-logo.svg
keywords:
- valkey
- redis
- cache
- database
- key-value
- in-memory
- nosql
maintainers:
- email: hello@cloudpirates.io
  name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: valkey
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/valkey
- https://github.com/valkey-io/valkey
type: application
version: 0.25.11-anvilkit.2
